logging:
  level:
    root: info
    #    com.zaxxer.hikari.HikariConfig: DEBUG
    #    com.zaxxer.hikari: TRACE
    org.hibernate:
      #      SQL: DEBUG
      orm.jdbc.bind: TRACE
  file:
    path: logs
spring:
  security:
    oauth2:
      client:
        provider:
          kakao: # not common OAuth2 provider
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver: # not common OAuth2 provider
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
          linkedin: # not common OAuth2 provider
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/userinfo
            jwk-set-uri: https://www.linkedin.com/oauth/openid/jwks
          amazon: # not common OAuth2 provider, docs: https://developer.amazon.com/docs/login-with-amazon/authorization-code-grant.html
            authorization-uri: https://www.amazon.com/ap/oa
            token-uri: https://api.amazon.co.jp/auth/o2/token
            user-info-uri: https://api.amazon.com/user/profile
            user-name-attribute: user_id
          twitter: # not common OAuth2 provider, docs: https://developer.amazon.com/docs/login-with-amazon/authorization-code-grant.html
            authorization-uri: https://twitter.com/i/oauth2/authorize
            token-uri: https://api.twitter.com/2/oauth2/token
            user-info-uri: https://api.twitter.com/2/users/me
            user-name-attribute: id
        registration:
          kakao:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: kakao
          naver:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: naver
          facebook:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: facebook
          google:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: google
            scope:
              - email
              - profile
          github:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - user:email
            client-name: github
          linkedin:
            client-id:
            client-secret: 
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: profile,email
          amazon:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: profile,profile:user_id
          twitter:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: users.read


