spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google1:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri:  https://www.googleapis.com/oauth2/v3/token
            user-info-uri: https://www.googleapis.com/userinfo/v2/me
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
        #          facebook:
        #            token-uri: https://graph.facebook.com/oauth/access_token
        #            authorization-uri: https://www.facebook.com/dialog/oauth
        #            tokenName: oauth_token
        #            authenticationScheme: query
        #            clientAuthenticationScheme: form
        #            userInfoUri: https://graph.facebook.com/me
        registration:
          kakao:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
          #            scope:
          #              - profile
          #              - account_email
          naver:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: naver
          facebook:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/facebook
            authorization-grant-type: authorization_code
            client-name: facebook
          google1:
            client-id:
            client-secret:
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/google1
            authorization-grant-type: authorization_code
            client-name: google
            scope:
              - profile
              - email
#server:
#  ssl:
#    key-store: classpath:ssl-keys/baeldung.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: baeldung
#    trust:
#      store: classpath:ssl-keys/baeldung.p12
#      store.password: 123456
#    enabled: true
